### ISSUE TITLE
histogram endpoint - review performance

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaDataService#10]
preliminary review indicates that subset service is returning in .125 seconds, but histo endpoint is 1.25.   since we have to do two sequential calls, the UX is almost 3 seconds for a histogram.

**Comment by d-callan** [comment]
so ive been looking at date histo EUPATH_0000096.EFO_0004950. profiling locally suggests that to 1) read this tabular data into R, 2) build my histo object in R, 3) convert to json and 4) write to file was taking total ~.5s.. ive gotten it to ~.3s. timing curl says ~1.5s.  i can only assume the rest of the slow is java. the search continues...

**Comment by d-callan** [comment]
some unnecessary and somewhat expensive logging has been removed. now down to ~1.3s. weve also found, much thanks to ryan, the most expensive bit seems to be writing data to disk for use in rserve. i can start to look into a java implementation for comparison.

**Comment by d-callan** [comment]
some more expensive logging removed, down to 600ms.
