### ISSUE TITLE
Should default bin width / number of bins reflect the viewport

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaDataService#11]
danielle raises this question.  we'll take it to the working groups and update this ticket when we learn more

**Comment by bobular** [comment]
Yes I think so.  When zooming in to a sub-range of the x-axis aka viewport, I think the client should not send a specific binWidth with the request and expect a default binWidth from the back end.  That default binWidth should "reflect the viewport" and provide semantic zooming.

The downside to this is that a user may have found a good binWidth and zoom just a little bit, and then the binWidth will be reset again.

**Comment by d-callan** [comment]
so far the only responses ive received have been in support of semantic zooming. since thats whats currently implemented im going to close this ticket. we can always reopen if someone voices concerns.
