### ISSUE TITLE
GEMS1 Case Control - Subset should be empty, but is not

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaDataService#111]
To reproduce:

1. choose Country = Bangladesh
2. go to Death Date variable
3. in histogram, select empty bins
4. note that counts of particpants are not zero, though it is zero in entity graph
![image](https://user-images.githubusercontent.com/43149795/135915387-f6b08e93-77ae-4a9d-a46e-9082747fb7f7.png)

**Comment by d-callan** [comment]
think this value "227 (1%)" is simply not responsive to the subset, and represents the total number of entities w data for that variable. this is confusing, and i think related to veupathdb/web-eda#511. im going to close this in favor of the existing issue in web-eda.
