### ISSUE TITLE
Hitting 500 errors and other errors on ELICIT

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaDataService#124]
If I try to look at ELICIT on qa.restricted.clinepidb.org, I can click through variables at first. However, after a couple of minutes, I hit the error message below. Once I hit it for one variable, I hit it for all variables, even ones that looked fine just 2 sec ago. 
<img width="778" alt="Screen Shot 2021-10-20 at 8 17 36 AM" src="https://user-images.githubusercontent.com/54597319/138100838-09f9b4a7-2a3d-46d1-8bf9-193f50431669.png">

If I try and clear my history with command+shift+R, I get the following error message for the study:

<img width="714" alt="Screen Shot 2021-10-20 at 8 18 29 AM" src="https://user-images.githubusercontent.com/54597319/138101007-e665348e-47ea-46eb-a856-69fe5bc3b5c5.png">

**Comment by d-callan** [comment]
i cant reproduce. possible this has already been resolved through another ticket in the two weeks since it was reported? @SheenaTomko can you check and close if you also cant reproduce?

**Comment by SheenaTomko** [comment]
This is now fixed. Closing
