### ISSUE TITLE
Bin slider config for date histogram currently only knows about days

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#13]
The binslider min max and step values returned for date histograms currently assume a unit of days. I figure we can revisit once we implement units properly.

**Comment by d-callan** [comment]
think we said to start we'll parse the units from the bin width (either provided or determined).

**Comment by bobular** [comment]
Hi @d-callan 

I have noticed this too.  Requests with

```{"studyId":"GEMSCC0002-1","filters":[],"config":{"outputEntityId":"EUPATH_0000096","valueSpec":"count","xAxisVariable":{"entityId":"EUPATH_0000096","variableId":"EUPATH_0010406"},"binWidth":"10 month"}}
```
return binSlider
```
{ min: 2, max: 1469, step: 1 }
```
Which I guess must be in days.  It ought to be in the same units as the returned binWidth if possible please.

(Or maybe (to discuss in a meeting), for dates, the binWidth slider should offer mixed units, e.g. 1 day, 1 week, 2 weeks, 1 month.  But for phase 2 maybe)
