### ISSUE TITLE
2x2 Mosaic: update parameter selection backend to allow users to select reference groups for all variables

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaDataService#130]
Related to: https://github.com/VEuPathDB/web-eda/issues/463

Statistics table was disabled for phase 1. The issue was that users could not select which reference group they wanted for x & y variables, and so the OR & RR seemed to be calculated "backwards" in many cases.

For Phase 2, we want to allow the user to determine the reference groups of interest for their analyses. This will require UI changes to the variable picker for the 2x2 table in Phase 2, similar to what is seen on the shiny apps on the WDK site. 

We may want to change verbiage of x-axis / y-axis to exposure / outcome
![image](https://user-images.githubusercontent.com/25450900/134096157-7e2353ef-b6c9-4149-9c36-9bf919ec446d.png)

Or, for diagnostic accuracy, diagnostic test result / correct outcome (gold standard test result): 
![image](https://user-images.githubusercontent.com/25450900/134096305-e7b08477-10b4-41da-8015-eb9d56fc8ef9.png)

Re-implement stats table (with p value, OR, and RR) after users can choose the reference group (like in shiny apps on live site).

**Comment by danicahelb** [comment]
Mockups were discussed in 1/14/2022 EDA UX meeting. Feedback has been integrated into mockups, but final sign off has not yet been obtained.

Mockups can be found here: https://docs.google.com/presentation/d/18_t5d7tAgyddOxdz4tdyfexdUOEPAprZt84Dk0N1h6s/edit#slide=id.g10c44382a45_3_40

**Comment by danicahelb** [comment]
see slack thread in [eda-workspace-ux](https://epvb.slack.com/archives/C0132PM1MT5/p1642526397035900) from Jan 18, 2022. still some questions that need to be addressed...

**Comment by danicahelb** [comment]
discussed in 8/29 EDA UX meeting. New figma mockups of Mosaic plot, 2x2 table viz tool UI: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=21%3A400

Dave suggested that it would be helpful to have the explanatory information open so that the user can refer to it as they are making their variable & value selections

Dan indicated that an explanatory information box that is open during parameter selection is also needed for many of the mbio apps

We will create a new explanatory information box feature; open by default until parameters are selected, then will auto-close (but the user can click to expand/reopen) 

We need to specify layout for variable & value selection, such that x-axis variable and value selectors are always on the same line; same for y-axis. For smaller screen sizes, stratification variable selector should wrap below variable & value selectors

**Comment by danicahelb** [comment]
This ticket is to update the parameter selection UI for the 2x2 mosaic plot. See final mockups here: https://www.figma.com/file/Su1eNm3Bby85CfrnX42L7q/2x2-table-UI?node-id=44%3A169&t=eO7GflQwHS5GJltr-0

Note: parameter selection layout needs to be refactored for 2x2 vis tool:
- 3-column layout saves space as all headers are on the same line
- Layout for variable & value selection should always place x-axis variable and value selectors on the same line; same for y-axis.
- For smaller screen sizes, stratification variable selector should wrap below variable & value selectors

**Comment by d-callan** [comment]
id estimate the backend work at a couple days effort, have a preference to not try to rush this into b61

**Comment by d-callan** [comment]
@danicahelb can you confirm if the stats we want to report are changing what was previously implemented? what we had done previously was report relative risk and odds ratio in the 2x2 and chi sq results in rxc. i see in figma sensitivity and specificity, and chi sq results for the 2x2. can you confirm that? and are we changing anything w rxc then?

**Comment by danicahelb** [comment]
@d-callan stats still need a bit of discussion. i will get this conversation prioritized amongst clinepi team and get back to you soon

**Comment by d-callan** [comment]
this is in data service v5.4.0 and rserve 5.1.0

**Comment by nkittur-uga** [comment]
This ticket will be QAed once the front-end tickets are implemented.

**Comment by nkittur-uga** [comment]
Reference group selection has been implemented and works well. QA is complete.
