### ISSUE TITLE
Viz tools: allow stratification vars to have >8 values & aggregating 

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaDataService#152]
In 2/23/2022 data viz meeting, we discussed the possibility of allowing overlay variables (and potentially also facet variables) to have any number of values; for variables with >8 values, we would aggregate those not belonging to the 'top 7'. This is how mapveu is handling variables with more values than colors.

currently, we have proposed to utilize derived variables to allow variables with >8 values to be used for overlays and facets. Once this is implemented, we should revisit this ticket to see if we would additionally like to aggregate values not in the top 7

**Comment by danicahelb** [comment]
Discussed in 4/4/2022 EDA UX meeting. This would be nice to also implement for the main variable on map visualizations

**Comment by d-callan** [comment]
this was revised from top 7 to user-selected 7 + other, and was handled in a different ticket
