### ISSUE TITLE
Date histogram response has gaps between binEnd and next binStart

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#16]
Something may be a little off with the date math, as the response to a query to date-histogram-bin-width
```
{"studyId":"GEMSCC0002-1","filters":[],
"config":{"outputEntityId":"EUPATH_0000096","valueSpec":"count",
"xAxisVariable":{"entityId":"EUPATH_0000096","variableId":"EUPATH_0010042"},
"binWidth":"3 month"}}
```
is giving "disjoint" bins:
"2007-11-01 - 2007-12-31", "2008-02-01 - 2008-03-31", "2008-05-01 - 2008-06-30"
note that January and April are missing.
![image](https://user-images.githubusercontent.com/308639/112550637-9566b580-8db7-11eb-8442-51e815c1002c.png)

This query on a different variable gives even stranger results:
```
{"studyId":"GEMSCC0002-1","filters":[],
"config":{"outputEntityId":"EUPATH_0000096","valueSpec":"count",
"xAxisVariable":{"entityId":"EUPATH_0000096","variableId":"EUPATH_0010406"},
"binWidth":"8 month"}}
```
![image](https://user-images.githubusercontent.com/308639/112550733-bfb87300-8db7-11eb-89dd-37d3a20a4f5d.png)

Smaller binWidths less problematic.

**Comment by bobular** [comment]
Just adding a note that binWidths >= '10 month' seem to be failing (for the GEMS date variables I've tested at least)

**Comment by d-callan** [comment]
believe both issues mentioned in this ticket are now resolved.
