### ISSUE TITLE
Lineplot 500 from categorical values with apostrophes/quotes

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#169]
With all three values in denominator, it's a 500. With just yes/no it's OK.

Might be the apostrophe. May need escaping somewhere.

GEMS1
![image](https://user-images.githubusercontent.com/308639/162792099-0cb2da5f-b681-4adf-979b-563f6055d68a.png)

**Comment by bobular** [comment]
Seems to be the apostrophe...

Also GEMS1: variable "Blood in stools"

**Comment by sweverschulman** [comment]
No longer receive 500 error when plotting the following plot.
<img width="920" alt="Screen Shot 2022-04-15 at 11 36 24 AM" src="https://user-images.githubusercontent.com/62298921/163590832-faa700b5-e502-4184-b09f-8029e3244898.png">
