### ISSUE TITLE
add support to validate variables by data shape and entity id as well as data type

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#17]
some vizs will care about both data shape and type, or about one or the other. but i think all vizs will care how the entities of each variable are related. ex: the dependent axis must be of the same entity or a child of the entity for the independent axis.
hoping ryan can provide some helpers to make this straight-forward-ish to implement and then pass it to me.

**Comment by ryanrdoherty** [comment]
Data service plugins are able to declare constraints on these properties; the validation is just not implemented yet.  Will open another issue (if not yet existing) to cover impl of constraint checking.
