### ISSUE TITLE
Line viz: improve mouse-over verbiage for non-compatible x-axis variables

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaDataService#174]
We need to improve the mouse over text for non-compatible variables for the x-axis of the line plot. We need to indicate that ordinal variables can be used on the x-axis. 

Updated verbiage: `Variable must be ordinal, a number, or a date and be of the same or a parent entity of the Y-axis variable.`

If it is possible to do this for b57, that would be nice. But it is not necessary, so I am marking it with a low priority label

<img width="352" alt="image" src="https://user-images.githubusercontent.com/25450900/163279453-c364cb8a-c7bc-48de-abd0-7f129dcaa12f.png">

**Comment by danicahelb** [comment]
we decided to not change "parent entity" text as part of this ticket. that language will be addressed in the future in https://github.com/VEuPathDB/EdaNewIssues/issues/249

Updated verbiage for this ticket should be: `Variable must be ordinal, a number, or a date and be of the same or a parent entity of the Y-axis variable.`

**Comment by aaronwlsong** [comment]
Looks good now. Closing ticket.

<img width="1704" alt="Screen Shot 2022-04-15 at 11 20 51 AM" src="https://user-images.githubusercontent.com/61077845/163589284-d0fe9087-d4ed-416b-961b-30c507fd3dc8.png">
