### ISSUE TITLE
Standardize capitalization on viz tools

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaDataService#179]
We have a mix of sentence and title case for each viz tool. These should all be the same. I have a slight preference towards sentence case. The fix should also be applied to viz tools that are not yet avialable (Density plot, Pie plot, etc.)
<img width="1000" alt="Screen Shot 2022-04-14 at 3 13 52 PM" src="https://user-images.githubusercontent.com/54597319/163468362-77467d86-3370-45bd-a93d-cf28ea6955d3.png">

**Comment by asizemore** [comment]
I'll be doing some data service work soon, so i might as well tackle this ticket, too!

**Comment by asizemore** [comment]
Closed with #210 
Deployed to feature mbio and qa clinepi

**Comment by danicahelb** [comment]
looks good! 

![Image](https://user-images.githubusercontent.com/25450900/189185047-75f2cfc1-ee44-47c2-8e60-7d0a91a20bf8.png)
