### ISSUE TITLE
Should default binWidth be rounded in the same manner as the binSlider min/max/step?

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#18]
I'd suggest the example below should return default binWidth: 1.8 (not 1.8421).  
https://localhost:3000/eda-subsetting-service/apps/pass/visualizations/numeric-histogram-bin-width 
```
# POST body
{"studyId":"GEMSCC0002-1","filters":[],"config":{"outputEntityId":"EUPATH_0000738",
"valueSpec":"count","xAxisVariable":{"entityId":"EUPATH_0000738","variableId":"EUPATH_0010346"}}}
```

```
# part of the response
{
	"binSlider": {
		"min": 0,
		"max": 17.5,
		"step": 0
	},
        "binWidth": 1.8421
}
```

Note that the step returned is zero (the client substitutes a default value of 0.1 when binSlider.step is missing or zero) - is this a case of rounding down and accidentally getting zero?

**Comment by d-callan** [comment]
plot.data v0.4.3 will round default binWidth to the same number of digits as is found on average in the underlying data. it also checks for binSlider values of 0.
