### ISSUE TITLE
Backend: improve dataElementDependencyOrder to allow facet and overlay to be mutually independent

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#190]
came up during a conversation w DSR where he was trying to approximately replicate a plot from a data provider and wasnt able to.

currently we can support a dependency order of visual elements defined something like:
'yaxis' -> 'xaxis' -> 'overlay' -> 'facet'

and wed like to be able to do something like:
'yaxis' -> 'xaxis' -> ['overlay','facet']

essentially stating that both the overlay and facet strata vars need to simply be the same or a parent entity of the xaxis, rather than the facet var being required as the same or parent of the overlay.

**Comment by dmfalke** [comment]
Are you thinking the property would have a nested array, e.g.: `['yaxis', 'xaxis', ['overlay', 'facet']]`?

**Comment by d-callan** [comment]
Tbh I hadn't thought much of anything yet.. do you have a preference?

**Comment by dmfalke** [comment]
I think a nested array, as above, works.

**Comment by sweverschulman** [comment]
@dmfalke and @d-callan - to confirm functionality. Facet and overly do not need to have the same entity level. Facet and overly does need to be the same entity level or parent of the axis?

**Comment by d-callan** [comment]
Worth spending a bit of extra time in the mosaics, the same logic/equivalency applies to the axes now. Should be sure they work as desired.

**Comment by sweverschulman** [comment]
I am messing around with RxC plot in Wash B Kenya. If I choose x-axis of “died” (participant) and y-axis cluster study arm. I am not allowed to choose ‘sex’ which has same parent as ‘died’. So I am a little confused at while it isn't allowing faceting

**Comment by d-callan** [comment]
@bobular i think somewhere i said that for the axes when equivalent, as in mosaic, to use the most ancestral entity between the two for the variable constraints dependency order.. but really we should be using the child most entity as the examples from steph and danica above illustrate. think this needs fixed front end. sry for the confusion.

**Comment by bobular** [comment]
> @bobular i think somewhere i said that for the axes when equivalent, as in mosaic, to use the most ancestral entity between the two for the variable constraints dependency order.. but really we should be using the child most entity as the examples from steph and danica above illustrate. think this needs fixed front end. sry for the confusion.

The strange thing is that I did implement it as childmost. (Though I forgot to rename one of the functions.)  But I will investigate deeper.

**Comment by bobular** [comment]
Ah, that was for determining the output entity.

In the main constraints handling I think I was still using the most-ancestral logic.

**Comment by bobular** [comment]
Fixed again in https://github.com/VEuPathDB/web-eda/pull/1446
Moving to "to be deployed"

**Comment by sweverschulman** [comment]
I was able to reproduce LLINEUP plot
