### ISSUE TITLE
Variable Constraints: Do not require overlay variables

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaDataService#197]
@jernestmyers noted when investigating [this issue](https://github.com/VEuPathDB/web-eda/issues/1177) that the data service is declaring overlay variables as required. I think this is just an oversight as we didn't explicitly say they are _not_ required (as we did with facets).

To Do

- [ ] For all visualizations where it makes sense (think about map!) set `isRequired` to false for overlay vars.

**Comment by danicahelb** [comment]
Note, on the front end, we indicate that what Ann refers to as the "overlay" term is the "Main variable". I don't know how this is handled on the backend

**Comment by asizemore** [comment]
@jernestmyers just confirming that the changes met your needs? (outside of the proportion requirements we discussed today)
If yes I'll count this as QA-ed and move it to Complete
