### ISSUE TITLE
Some compatible variables are not allowed to choose in plots

### ISSUE THREAD

**Issue by aaronwlsong** [VEuPathDB/EdaDataService#199]
Some compatible categorical vars are not allowed in plots.
 eg. In Jilinde prospective cohort study, barplot, "Self-defined gender" and "Sex" should both be allowed but are greyed out
<img width="553" alt="Screen Shot 2022-06-28 at 4 55 51 PM" src="https://user-images.githubusercontent.com/61077845/176288662-163b37b5-5ee9-4960-b3ac-0eac788abcfd.png">.

eg. In Jilinde prospective cohort study, r*c mosaic plot, var "Self-defined gender", "educational level" and "Sex" should be allowed but are greyed out.
<img width="829" alt="Screen Shot 2022-06-28 at 5 12 30 PM" src="https://user-images.githubusercontent.com/61077845/176289046-517fa9ed-1ed9-431a-943e-7df6fa9073f0.png">

eg. In Jilinde prospective cohort study, box plot, var "Self-defined gender", "educational level" and "Sex" should be allowed for x-axis but are greyed out.
<img width="618" alt="Screen Shot 2022-06-28 at 5 20 36 PM" src="https://user-images.githubusercontent.com/61077845/176294864-83e72c88-732e-43e4-950e-628ac8780163.png">

**Comment by dmfalke** [comment]
Not sure if this has to do with incorrect variable constraints or incorrect data types. Putting in EdaDataService as a starting point.

**Comment by SheenaTomko** [comment]
@aaronwlsong can you test if this is still an issue?

**Comment by aaronwlsong** [comment]
It seems that the issue still exists. 

![Image](https://user-images.githubusercontent.com/61077845/178568130-764732e0-5b85-49d8-88ed-f920e0821740.png)

**Comment by SheenaTomko** [comment]
Weilu discovered he needs to make some conversion file changes. Closing this ticket
