### ISSUE TITLE
bin data to have binStart and binEnd

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#2]
There's some debate over whether or not binLabel is needed any more after binEnd is returned by the data plugin.

The client will definitely want a binLabel for mouse-over, however creating a **concise** bin label is non-trivial, especially for dates.

**Comment by bobular** [comment]
binLabel construction seems more like a clienty thing to me.

**Comment by d-callan** [comment]
so what i get back from R is actually the label, which im parsing for start + end. so ive no problem returning it since ive got it in hand anyway. once we dig into perf and have java versions of the plugins my opinion may change, idk.

**Comment by d-callan** [comment]
binEnd has been added, and binLabel remains
