### ISSUE TITLE
All scatterplots should accept dates, integers, and numbers

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaDataService#200]
Make the var constraints of alpha div and ranked abundance scatterplots match the pass app scatter's constraints.

**Comment by asizemore** [comment]
@SheenaTomko @danicahelb would one of the clinepi members mind taking this issue for qa?
To QA, go to either ranked abundance or alpha div scatterplot, and pick a variable that is an integer. Integer variables should work now :)

**Comment by SheenaTomko** [comment]
looks good, tested both ranked abundance and alpha div scatterplots
