### ISSUE TITLE
Visualizations: 2x2 constraints should depend on number of distinct values rather than a binary data shape

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#208]
if a variable w 2 values also is ordinal, then we want it in the 2x2 viz. right now the 2x2 wont allow this bc its looking for a 'binary' data shape. instead the constraints should be built from the number of unique values.

**Comment by SheenaTomko** [comment]
This was discovered in MORDOR when the variable "Sex" had ordinal values. This may be changed on a reload before this ticket is ready for qc.

**Comment by d-callan** [comment]
this looks to be complete on the backend. im going to close, and we can reopen if it turns out that ive missed something.

**Comment by aaronwlsong** [comment]
Looks good when in MORDOR 2*2 mosaic plot IF choose x=sex, y=died. But if the order is reversed, say when x=died, y=sex. Hitting the 502 bad gateway error.

**Comment by aaronwlsong** [comment]
Looks good when in MORDOR 2*2 mosaic plot IF choose x=sex, y=died. But if the order is reversed, say when x=died, y=sex, then it hits the 502 bad gateway error.


![Image](https://user-images.githubusercontent.com/61077845/220195440-4d829125-735b-47d9-864e-d732086aa889.png)

**Comment by danicahelb** [comment]
this seems fixed now


![Image](https://user-images.githubusercontent.com/25450900/223845846-dbdc5a73-39dd-4a5c-817e-bc37938445bc.png)




![Image](https://user-images.githubusercontent.com/25450900/223845929-d12ea996-41b8-431f-80fc-c0578b5d8549.png)
