### ISSUE TITLE
Visualizations: improve order of mbio vizs

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#209]
seems to me like histogram should probably be listed first under distributions, barplot first under counts and proportions etc. i also noticed a few places where sometimes plot was lower case and other times upper like 'Line plot' and 'Bar Plot'..

**Comment by asizemore** [comment]
Yeah good call. There's already an [issue](https://github.com/VEuPathDB/EdaDataService/issues/179) for the capitalization. I can handle both of these if helpful

**Comment by asizemore** [comment]
deployed to feature mbio.

**Comment by SheenaTomko** [comment]
Looks great!
