### ISSUE TITLE
Mosaic plot (2x2) has variable constraint issue with terms allowed for x-axis and y-axis

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaDataService#213]
We discussed the variable constraint issue with 2x2 Mosaic Plot viz tool in 9/12/2022 EDA UX meeting.

Currently, the table cannot be set up properly for many Exposures of interest
- Proper set up: Outcome on the X-axis and Exposure on the Y-axis
- Issue: outcomes are often under “Sample” category, while exposures are often under “Household”, “Participant”, or “Participant repeated measures” categories

@d-callan proposed possibly “recycling” other variable constraint fixes, like revising data dependency order to allow facet & overlay to be independent: https://github.com/VEuPathDB/EdaDataService/issues/190 (also possibly related to https://github.com/VEuPathDB/EdaDataService/issues/119)

Danielle, can you take a look and see what the best approach for fixing the variable constraint issue will be? thanks!

**Comment by sweverschulman** [comment]
I went to run a 2x2 plot in India ICEMR Cohort and received the following error. 

![Image](https://user-images.githubusercontent.com/62298921/200023213-713ba547-4c00-4390-b80f-b3392f49d5e6.png)

`Unexpected backend type(s) encountered: Invalid value null' supplied to relativerisk (type: number) of O (type: Partial<{ oddsratio:
(number | null), pvalue: (number | string), orInterval: string, rrinterval: string, relativerisk: number, facetVariableDetails: (I({ entityld:
string, variableld: string ) & ( value: string })I | [(( entityld: string, variableld: string ) & ( value: string }), (( entityld: string, variableld:
string } & { value: string })]) }>) of statsTable (type: Array<Partial<{ oddsratio: (number | null), pvalue: (number | string), orInterval:
string, interval: string, relativerisk: number, facetVariableDetails: ([({ entityld: string, variableld: string } & { value: string })] I [(f
entityld: string, variableld: string } & { value: string }), ({ entityld: string, variableld: string } & { value: string })!) }>>) of 1 (type:
Partial<{ statsTable: Array<Partial<{ oddsratio: (number | null), pvalue: (number | string), orInterval: string, rrinterval: string,
relativerisk: number, facetVariableDetails: ([({ entityld: string, variableld: string } & { value: string })I | [({ entityld: string, variableld:
string } & { value: string }), (( entityld: string, variableld: string ) & { value: string })I) }>>, completeCasesTable: Array<Partial<{
completeCases: number, variableDetails: ( entityld: string, variableld: string ) ]>> }>) of [root] (type: ({ mosaic: ( data: Array«(f
xLabel: Array<string>, Label: Array<Array<string>», value: Array<Array<number>> } & Partial<{ facetVariableDetails: (I({ entityld:
string, variableld: string ) & ( value: string ))I | [(( entityld: string, variableld: string } & ( value: string )), (( entityld: string, variableld:
string } & ( value: string })I) }>)>, config: ( completeCasesAlIVars: number, completeCasesAxesVars: number, ×VariableDetails: (
variableld: string, entityld: string ), yVariableDetails: ( variableld: string, entityld: string ) ) ), sampleSizeTable: Array<{ size:
Array<number> }>, completeCases Table: Array<Partial<{ completeCases: number, variableDetails: { entityld: string, variableld:
string }}>> } & Partial<{ statsTable: Array<Partial«{ oddsratio: (number | null), pvalue: (number | string), orlnterval: string, rrinterval:
string, relativerisk: number, facetVariableDetails: ([({ entityld: string, variableld: string } & { value: string })] | [({ entityld: string,
variableld: string ) & ( value: string )), (( entityld: string, variableld: string ) & ( value: string })]) }>>, completeCasesTable:
Array<Partial<{ completeCases: number, variableDetails: ( entityld: string, variableld: string } )>> }>))`

**Comment by d-callan** [comment]
i think we need a new issue for this error @sweverschulman 

and i need to know from maybe @bobular or @dmfalke if there is something better than null that i can send when we cant calculate something like relative risk for the 2x2

**Comment by danicahelb** [comment]
new ticket created: https://github.com/VEuPathDB/EdaNewIssues/issues/462

**Comment by danicahelb** [comment]
@d-callan I'm QA'ing this ticket with WASHb Bangladesh

the outcome i want to investigate is "Diarrhea case during the last 7 days, by caregiver report"
- binary values: yes / no
- participant repeated measure

the exposure i want to investigate is "Chlorine detected in stored drinking water"
- binary values: yes / no
- household repeated measure

i am unable to select the household repeated measure variable of "Chlorine detected in stored drinking water" for the y-axis (exposure) when the participant repeated measure variable of "Diarrhea case in the last 7 days" is selected for the x-axis (outcome)

<img width="497" alt="image" src="https://user-images.githubusercontent.com/25450900/200436047-62283d43-3dab-470f-afe8-941cfc8045e0.png">

the message i get as to why this wont work is "Variable must have exactly 2 unique values"...which it does. I suspect the issue is repeated measures

**Comment by danicahelb** [comment]
@d-callan confirmed that we get this issue when we select participant repeated measures for x-axis and household repeated measures for y-axis. 

It's currently disallowed primarily bc the merge service doesn't know how to merge across different branches of the tree. 

Danielle can update the help text there in the short term. But upgrading the merge service is probably a big task.

**Comment by danicahelb** [comment]
closing this ticket.

new ticket to address plotting repeated measures terms at different entity levels: https://github.com/VEuPathDB/EdaNewIssues/issues/464

new ticket to update help text: https://github.com/VEuPathDB/EdaNewIssues/issues/465
