### ISSUE TITLE
mbio subsetting results table preview not showing up

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaDataService#226]
for microbiomeDB MALED 2yr & MALED diarrhea studies, the subset results user configured table preview does not appear for 16S rRNA (V4) assays. (i haven't checked to see if the issue also is occurring in other studies)

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/25450900/206312963-d1aecb01-f5f2-443d-9008-c78b4107a82a.png">

**Comment by danicahelb** [comment]
@dmfalke did you make the other issue? if so, can you link it here?

**Comment by danicahelb** [comment]
now we are getting a server error when previewing table for 16S subset results, Metagenomic sequencing assays (and possibly other results tables that are not standard entities of participant, participant repeated measure, sample, etc...i didn't check all)

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/25450900/221257654-3ad0e7ff-a5d3-469e-ae6e-91f89eeca96c.png">

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/25450900/221258204-94ba727b-7dc2-4218-b4b3-aa033b27f977.png">

**Comment by ryanrdoherty** [comment]
The plot thickens.  I tried to recreate this and it did error on assay download but it's not because of the 1000 columns.  The stack trace says "Table does not exist" which is true of table eda.attributes_MALED_healthy_1_entity_16SRRNAV4Assay.  The other three entities are there.  I'll post in slack.

**Comment by ryanrdoherty** [comment]
This seems to be resolved.
