### ISSUE TITLE
Apps: Constrain collections for apps?

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaDataService#227]
Do we need to constrain on individual collections or can we get away with constraining at the assay level?

From the frontend perspective, it would be helpful for the data service to declare which type of collections are usable for each app in the endpoint.

**Comment by asizemore** [comment]
we have the following types of collections
- taxonomic abundance
- functional
- coverage? Most useful in context with the abundance data. Possibly as a filter for abundance. Let's hide for now.
- pathway abundance. Would have a specific app that uses pathway maps. Coverage useful here. But taxonomic abundance collections don't make sense here.
- metabolomics (FARMM)

Nothing pressing for now, but we should work on it soon. Not needed for FARMM nor for beta site to go live. Lower priority than Correlations app.

**Comment by asizemore** [comment]
Another really helpful annotation for collections would be "item" or "element" that's filled in like "taxon" or "pathway" or "enzyme". A plural form would also be nice :) but the idea being that our interface will be more clear if we can refer to a list as a "list of taxa" vs a "list".

**Comment by asizemore** [comment]
These collection annotations are important for vizs as well. For example, we've learned that genomics expects volcano plots to have one type of language but mbio expects it to have another. It would be easy for the language to vary based on the type of data the plot is showing.
(would be handled in the web-eda visualization)

**Comment by asizemore** [comment]
also i'll reach out to ryan to see if we can already do something like the compute plugin declaring constraints.

**Comment by asizemore** [comment]
Allrighty. Here's an initial list of the annotations:

- displayName
    - Used when populating dropdowns. Ex: “16S Phylum”, “z-scores”
- displayRange
    - Used for setting default axes. Ex: [0, 1]
- target
    - The units of the collection. Ex: “taxon”, “gene”
- targetPlural
    - for displaying information about calculations or a plot, such as “Showing 800 of 803 taxa”. Ex: “taxa”, “genes”
- isNormalized
    - boolean describing if the collection has already been normalized.
    - I also considered isCompositional, but technically absolute abundance is compositional. So isCompositional is a different flag. Normalized data is compositional but the other direction is not guaranteed
- dataType
    - we discussed recently having non-numeric collections (tick data). Would also be good for presence/absence corrale data.
- dataShape
    - same reasons as for dataType

@dmfalke to make sure i understand, server-side constraint checking would be like what the vizs in the data service do to constrain against categorical vars in scatterplots, right?

**Comment by dmfalke** [comment]
> @dmfalke to make sure i understand, server-side constraint checking would be like what the vizs in the data service do to constrain against categorical vars in scatterplots, right?

I was thinking about if we would want the compute service to apply constraints when a request is received, in an automated way. E.g., compare the request with some constraint declaration, and return a 4XX response if they don't match. But, as I'm writing this, it seems unlikely this will be done.

On the other hand, it might be best to follow suite with viz plugins and declare constraints in compute plugins. It can still be up to the client to apply those constraints.

Thoughts?

**Comment by d-callan** [comment]
i think it makes sense for the compute plugins to declare and validate against constraints. i could see writing a constraint against the 'target' annotation that ann is proposing, so we know we arent passing genes to an analytical method that will either err or produce bogus results for that type of data.

**Comment by d-callan** [comment]
@asizemore have you checked what we already have for collections? its possible we have display names, ranges etc already for ex. to me, target, targetPlural and isNormalized are the key guys for this ticket, and maybe the only ones we dont already have.

**Comment by d-callan** [comment]
Distribution defaults should have the display range i think

**Comment by asizemore** [comment]
Closing in favor of https://github.com/VEuPathDB/service-eda-compute/issues/57
