### ISSUE TITLE
Standalone map: create new "pass-through app" for map marker and viz endpoints

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#237]
Although the regular EDA and Map viz plugins will share a lot of code, it makes sense to separate their APIs so they can be customised cleanly as needed.

For example, we can get rid of the facet variable for all the map viz's

Also birds eye and completeness data may not be needed for the SAM

**Comment by d-callan** [comment]
I think this includes the map-marker-overlay plugin, which is planned to be significantly reworked w a focu son performance for SAM as compared to EDA

**Comment by SheenaTomko** [comment]
Nothing to QA for now. We will qa the maps through front-end tickets
