### ISSUE TITLE
Standalone map: categorical overlay, update API for customisable N<=7 + other 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#238]
The new-improved handling of categoricals including high-cardinality vars as discussed [here](https://veupathdb.atlassian.net/wiki/spaces/WG/pages/181796873/2023-02-02+Map+UX) is to
- if the variable has >8 values, continue to overlay most-populous-7-in-viewport + pooled Other as the **default** (did we actually agree this?)
- if a list of up to 7 values are provided in the request, overlay by these + pooled Other, even if the variable has <=8 values

Approx task list
- [ ] handle POST payload in EdaDataService
- [ ] implement necessary R functions
- [ ] deploy to `map-markers-overlay` endpoint
- [ ] deploy to `lineplot` endpoint (as highest priority of the visualizations)
- [ ] deploy to other vizs

**Comment by d-callan** [comment]
depends on https://github.com/VEuPathDB/plot.data/issues/205
