### ISSUE TITLE
Standalone map: plugin to find bin ranges for continuous variables based on subset

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#239]
As discussed here: https://veupathdb.atlassian.net/wiki/spaces/WG/pages/181796873/2023-02-02+Map+UX 

Default behaviour could continue to be equal spaced bins using global min & max

However, we want the binning to use the subset min and max (ignoring viewport) which will require a separate back end request to calculate this.

Then also consider quantile and SD-based binning.

Approx task list

- [ ] new `continuous-var-bin-spec` (feel free to rename) end point, calculates min, max and equal binWidth 
- [ ] add quantile-based bin mode for `continuous-var-bin-spec` (again this needs to be calculated on the subset, not the viewport-ed subset) - this presumably returns a list of binStarts and ends or similar
- [ ] ~~allow `map-markers-overlay` to handle quantile binSpec~~
- [ ] similar approach for SD-based binning (but probably for Phase X)

**Comment by d-callan** [comment]
i think for consistency the new endpoint should always return bin start and ends. then the client just passes those to map-markers-overlay, which doesnt need to know anything about binning specific binning methods
