### ISSUE TITLE
pass/histogram returns malformed binWidth values for dates

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#25]
Here is a config.binSpec part of a response for a date variable that where the default binWidth is 1 month:

```
{
	"binSpec": {
		"type": "binWidth",
		"value": "month",
		"units": "month"
	}
}
```

It would also be great to fix the `incompleteCases` return type (plain `number`);

**Comment by d-callan** [comment]
these should both now be resolved.
