### ISSUE TITLE
standalone map floating boxplot `evilMode` deprecation needs fixing

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#272]
I looked at barplot which is passing `noVariables` to the `evilMode` argument but boxplot is passing `false` which is causing a 500

```
Error in veupathUtils::matchArg(evilMode) : 
'arg' should be one of “noVariables”, “allVariables”, “strataVariables”
```

https://github.com/VEuPathDB/EdaDataService/blob/master/src/main/java/org/veupathdb/service/eda/ds/plugin/standalonemap/FloatingBoxplotPlugin.java#L126-L136

Should probably use the same approach as barplot?

We should look at the other endpoints too, in case the same thing is there.

**Comment by asizemore** [comment]
Is the plan to always hardcode the missingness option? Do we want to listen to what the client has to say or no, just always pass `"noVariables"`?

**Comment by asizemore** [comment]
If indeed the data service should always hard code the missingness argument, please see the linked [PR](https://github.com/VEuPathDB/EdaDataService/pull/273)
