### ISSUE TITLE
Map bubble mode: Need backend endpoint to provide ranges for bubble size and gradient legends

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#287]
it will be important for the bubble map that the legends, both bubble size and gradient color, are mapped to ranges based on the subset rather than the visible data. this could be complicated bc:

1. for the bubble size this is based on entity counts, and expected counts might change based on geohash level etc. it probably makes sense for the theoretical min to be 1 since these are counts, and the theoretical max should probably be based on the least granular geohash level..
2. for the gradient this represents summary values rather than raw values so it may not make sense to rely on the data ranges in the metadata. plus we also face the geohash and viewport impacting the range problem. if we assume for now (which @bobular will have to confirm) that a more granular geohash is always within a less granular one.. then maybe we can take summary values from the most granular geohash and use the min and max of those values?

i have to think about this more when less tired to make sure ive got the logic right here

**Comment by d-callan** [comment]
is it possible this is the bubble marker endpoint itself? and its the clients job to pass the whole world as a viewport, and the appropriate geohash level, to get the data it needs to build the legend?

**Comment by bobular** [comment]
> 1. the client makes a request to bubble markers w the most granular geohash and the whole world as viewport

Sorry to see this late.  I'm worried that asking for fine-grained geohash on the whole-world will create a huge response.

What work was done to complete this ticket? I don't see any linked or mentioned issues. Is that because we'll use the existing bubble marker endpoint?

**Comment by dmgaldi** [comment]
Hey Bob, sorry I thought I linked the PR #293.

For the legend, the response size shouldn't be proportional to the aggregation level since it's aggregated to min/max values.
