### ISSUE TITLE
Change beta div scatterplot name

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaDataService#288]
Change to "beta div dimensional reduction plot"?
Definitely need to change it to something. Get finalized name from @dpbisme

**Comment by asizemore** [comment]
deployed to qa. Working on q1 and q2. @danicahelb mind qa-ing please?

**Comment by danicahelb** [comment]
Looks good now!
<img width="663" alt="image" src="https://github.com/VEuPathDB/EdaDataService/assets/25450900/30232e63-e2cd-4cc9-8cfd-992f19467daf">
