### ISSUE TITLE
*-histogram-num-bins should return binWidth

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#3]
which will be a number for numeric and a "time delta" string like "2 weeks" for dates.

A nice thing to have (which hasn't been discussed anywhere IIRC) would be an option to have the binStarts and binWidth rounded to "something sensible", though this might mean that a request for 10 bins might return 9 or 11.

**Comment by d-callan** [comment]
can you clarify? i assume im missing something obvious, but whats the use case where using the *-histogram-bin-width endpoints is not sufficient if what you want back is a bin width?

**Comment by d-callan** [comment]
im rounding the binSlider config in the response, but not the binWidth. im not sure im comfortable returning a different number of bins than was requested..

**Comment by bobular** [comment]
I think the binWidth needs to be returned in the response so that the client knows where the binWidth slider should be by default, when the original back end request didn't specify bin width and was expecting the sensible default.

**Comment by bobular** [comment]
Issue #5 is also a use case.

**Comment by d-callan** [comment]
Yes. I understand that when a default is calculated it needs returning. The endpoints return binWidth in the same format it's requested. So *-histogram-num-bins both accepts and returns num bins. What I'm trying to understand is why you aren't using *-histogram-bin-width

**Comment by d-callan** [comment]
Actually even the bin slider config is in numbins for the num bins endpoints. That's all it knows about, on purpose, currently.

**Comment by bobular** [comment]
You're right - we're using *-histogram-bin-width for all the client work at the moment, and that does return config.binWidth

If the *-histogram-num-bins version was used you're right that the slider should be for the number of bins.

I think I was confused when I didn't know about the returning of the sensible default (and thought the num-bins requests were the way to get that sensible default).

Closing this ticket. Thanks!
