### ISSUE TITLE
Problem with 'latest' /apps/pass/visualizations/histogram on dfalke-b.clinepidb.org 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#30]
The following request POST body works on feature.clinepidb.org but gives a 500 error on dfalke-b.clinepidb.org
@dmfalke @d-callan 

```
{
	"config": {
		"binSpec": {
			"type": "binWidth"
		},
		"outputEntityId": "PCO_0000024",
		"valueSpec": "count",
		"xAxisVariable": {
			"entityId": "PCO_0000024",
			"variableId": "EUPATH_0000714"
		}
	}
}
```

```
Error: 500 Internal Server Error
{"status":"server-error","message":"Unable to complete processing","requestId":"7SVk99P3k1d5kj1mpDwojN"}
```

I am told dfalke-b is hosting the latest main/master branches of the data services repos.

As far as I can tell, the POST data above conforms with the latest API docs at https://veupathdb.github.io/EdaDataService/api.html#resources:/apps/pass/visualizations/histogram:post

(categorical barplot requests are working fine for me, btw)

**Comment by d-callan** [comment]
some recent changes to the rserve image to add packages mbio will need were clobbering the plot.data fxn names. the rserve image has been updated to in-house packages get attached last and take priority, and the data service has been updated to use the plot.data namespace explicitly.
