### ISSUE TITLE
barplot incompleteCases might not be correct

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#32]
Example GEMS->Household->Fetch drinking water everyday

In the EDA image below (on this [branch/PR](https://github.com/VEuPathDB/web-eda/pull/85)), we have to calculate the 17,057 by summing the background totals for yes and no.
Should we be able to calculate it using `22567 - incompleteCases` ? 
![image](https://user-images.githubusercontent.com/308639/117978846-34c11700-b32a-11eb-8f0a-fa5f533ebde2.png)

incompleteCases is zero for the following barplot request
```
{
	"config": {
		"outputEntityId": "PCO_0000024",
		"valueSpec": "count",
		"xAxisVariable": {
			"entityId": "PCO_0000024",
			"variableId": "EUPATH_0010234"
		}
	},
	"filters": [],
	"studyId": "GEMSCC0002-1"
}
```
response:
```
incompleteCases: 0
```

**Comment by bobular** [comment]
Please check also the response from `histogram`

**Comment by d-callan** [comment]
so the subsetting service doesnt return data to me if there isnt any. as a consequence, currently incompleteCases really only applies if multiple variables are requested, and a particular record has values for one var and not another. it doesnt currently capture the number of records where all vars (in this case just the one) are missing data.. if it has to be able to do this, i guess i have to have plugins always make a second request to find the total number of expected records, and do some math.

**Comment by dmfalke** [comment]
I think the plan is (or should be) for variable metadata to include this number.

**Comment by dmfalke** [comment]
I talked to Steve. This is the plan that makes sense to us.

1. The `/counts` endpoint can be used to get the total number of household for a given _subset_.
2. The response for a viz plugin will include the table of incomplete cases.

For the subsetting tab, we can use this information for the _background_ to derive the stats.

**Comment by d-callan** [comment]
response for viz plugins updated to always include a table of complete cases in plot.data v0.5.12, data service v0.1.6
