### ISSUE TITLE
Map - international/utf-8 characters are still mangled in UI - could be subsetting and analysis plugin back ends?

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#323]
https://redmine.apidb.org/issues/52715

See the fourth entry in the subsetting table below for the megastudy (live site or https://feature.vectorbase.org at time of writing)
Also the vast majority of Vietnamese locations are problematic (as one example).

![image](https://github.com/VEuPathDB/EdaDataService/assets/308639/5f4150a8-564b-44e2-af52-7bfe9e149734)

@jbrestel and I are pretty sure the data are loaded into Oracle correctly.

Please could someone check the back end (and the binary file system?) is doing the Right Thing w.r.t. special characters?

**Comment by bobular** [comment]
The plot thickens...

Downloads are looking good

![image](https://github.com/VEuPathDB/EdaDataService/assets/308639/83c86b1d-e36c-4679-b34f-c67b924c99ca)

**Comment by bobular** [comment]
Here's a subsetting distribution response - fragment copied from dev tools:

```
{
	"89": {
		"value": 3,
		"binStart": "B?c Lieu (Vietnam)",
		"binEnd": "B?c Lieu (Vietnam)",
		"binLabel": "B?c Lieu (Vietnam)"
	}
}
```

And here's similar from a map markers response

```
{
	"overlayValues": [
		{
			"binLabel": "Archipelago (?land)",
			"value": 1,
			"count": 1
		}
	]
}
```

**Comment by aurreco-uga** [comment]
the client is getting correct international chars  from the service in variable definitions but not in variable values (seen on inspect).
the fact that var defs and values  show the same in the database, makes me think loaders are loading chars correctly.
so i would check the service, if ther eis anything different between a var def and  var value.
unfortunately we dont have a def in vb with int chars, the one i have  (nupur pointed out to me) is attached (score crt, gestational age) 
![Screenshot 2023-10-03 at 5 29 06 PM](https://github.com/VEuPathDB/EdaDataService/assets/16354313/1c18b244-cd73-48d6-8981-85366dd182a6)

**Comment by dmgaldi** [comment]
As far as I can tell, for the variable distribution there's nothing wrong on the backend. If I run this query DBeaver or SQLPlus, the special characters are not rendering correctly:

```
SQL> SELECT DISTINCT string_value FROM eda.attributevalue_VBP_MEGA_CollectionSite WHERE attribute_stable_id = 'ENVO_00000005' AND string_value LIKE '%Norway%';

STRING_VALUE
--------------------------------------------------------------------------------
?stfold (Norway)
Aust-Agder (Norway)
Buskerud (Norway)
Oslo (Norway)
Vest-Agder (Norway)
Vestfold (Norway)

6 rows selected.
```

I'll try to understand how the download is working next.

**Comment by dmgaldi** [comment]
Looks like the wide table renders correctly. @bobular @jbrestel Is it possible there's some difference in the way we're handling international characters in the tall table vs. the wide table?

```
SELECT DISTINCT ENVO_00000005 FROM eda.attributes_VBP_MEGA_CollectionSite;
```

**Comment by jaycolin** [comment]
Yes, the tall table is loaded differently -- using sqlldr -- so I believe this is Oracle-specific and can be fixed by: at loading time, the data loader must set/export environment variable NLS_LANG=AMERICAN_AMERICA.UTF8 before running reflow. I'll follow up once I have loaded some popbio loaded into eda-inc.

**Comment by jaycolin** [comment]
Can someone give me the URL from the screenshot? I have no idea how to get to that page

**Comment by jaycolin** [comment]
The popbio datasets are now correctly loaded as described above, looks correct in my browser
