### ISSUE TITLE
eda and correlation app for plasmo

### ISSUE THREAD

**Issue by jbrestel** [VEuPathDB/EdaDataService#348]
eda and correlation app for plasmo.

Similar to what we do for vectorbase / map.  We also need the correlation app from mbio

**Comment by dmfalke** [comment]
There are two correlation apps: `correlationassaymetadata` and `correlationassayassay`. @jbrestel can you clarify which app you want to use w/ plasmo? Thanks!

**Comment by dmfalke** [comment]
Can this be closed?

@d-callan @asizemore @jbrestel

**Comment by asizemore** [comment]
Yes!
