### ISSUE TITLE
need a simpleHistogram for subset tab

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#35]
think this is a new plugin/ endpoint. has a unique data flow, getting data from the distribution endpoint in ss, and bypassing ms. will receive a range and binWidth, and bin in Java in a single pass.

**Comment by d-callan** [comment]
need simpleBar too

**Comment by d-callan** [comment]
talked w ryan about this. think he means to implement this himself, in the subset service.

**Comment by d-callan** [comment]
Needs to return the number of entities w 1 value, 2 values etc.. to well accommodate the multivalued vars

**Comment by ryanrdoherty** [comment]
This is mostly done.  Remaining TODOs are documented here:
https://trello.com/c/b8l2b1yj/1625-eda-remaining-subsetting-histogram-work
