### ISSUE TITLE
*-histogram-bin-width chooses a sensible bin-width if none requested

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#4]
I think this is already implemented? - Just adding here in case it isn't.

**Comment by d-callan** [comment]
so the logic currently is something like this:
(though maybe i should ask if this is meant to happen before or after adjustment based on the viewport?)

```
if (is.null(binWidth)) {
    if (length(x) < 200) {
      binningMethod <- 'sturges'
    }
    skewness <- moments::skewness(x)
    if (abs(skewness) > .5) {
      binningMethod <- 'doane'
    }
    if (is.null(bins)) {
      binningMethod <- 'fd'
    }
  }
```

**Comment by dmfalke** [comment]
It seems like this might be an issue, then.

**Comment by dmfalke** [comment]
Sorry, I missed the question about viewport. We should seek clarity.

**Comment by steve-fischer-200** [comment]
it seems as tho danielle is already providing a sensible default.  so i am closing this
