### ISSUE TITLE
TwoByTwo viz: Using variables from different entities gives a 500

### ISSUE THREAD

**Issue by chowington** [VEuPathDB/EdaDataService#41]
Example:

![image](https://user-images.githubusercontent.com/12377649/121040773-2bd43180-c780-11eb-8361-493c02af610e.png)

Sex (from Participant entity) and Undernutrition (from information of process)

**Comment by d-callan** [comment]
this is another merge service bug. if i make this request to it: ```{"studyId":"GEMSCC0003-1","filters":[],"entityId":"EUPATH_0000096","outputVariables":[{"entityId":"EUPATH_0000096","variableId":"PATO_0000047"},{"entityId":"EUPATH_0000738","variableId":"EUPATH_0015119"}],"derivedVariables":[]}``` i get all nulls for undernutrion

**Comment by ryanrdoherty** [comment]
Message to Dave about this:
I figured out the problem with the null columns (missing data) when you swap the vars sometimes.  The requested entity ID is wrong.  You can only select vars that belong to the target entity or its ancestor.  So if you're trying to visualize participants, you can't use an observation var (at least until derived vars come along that summarize the values into a participant var).  Don't know how you're selecting the entity to request, but if any of the vars belong to a descendant entity, you need to pick the descendant.  Maybe we can have the data service perform this change but I think that obscures the actual API requirements.  I've added validation to the merging service to describe the problem, but another bug in the core lib (that Ellie needs to fix) is obscuring that message and throwing 500.  Anyhow, if you can swap the entity on the client we'll at least stop having missing data in this case.

**Comment by d-callan** [comment]
Think the requested entity should always be whatever the first guy in the var dependency order is..

**Comment by ryanrdoherty** [comment]
Danielle, is this resolved then?

**Comment by d-callan** [comment]
maybe im not following some part of this conversation... but it seemed you were saying its failing bc the outputEntity requested by the client is wrong? and you said you didnt know how @dmfalke was determining which entity to request. i was trying to say that dave should always use the entity associated w the variable that is listed first in the plot element dependency order.. and if thats not what hes doing, then maybe this is a client issue?

**Comment by dmfalke** [comment]
In this case, I think we're using the x-axis variable, but y-axis is the first element in that array. Can this rule be generalized? Are there any plugins that do not have a dependency order? Can we just pick an arbitrary element, in that case?

**Comment by dmfalke** [comment]
But the point is, this is a client bug.

cc @chowington

**Comment by d-callan** [comment]
Think it's a general rule, and all vizs w more than a single var should be expected to have a dependency order.
