### ISSUE TITLE
Map markers plugin

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#42]
Needs to have a display name of 'Geo-spatial Map' or something similar. Also need to figure out if the little bar and histograms should be incorporated into this plugin (basically a multi-plot viz)

**Comment by bobular** [comment]
For reference, here are some related ramblings on Slack by me:

> If we made a map visualisation for EDA, if no overlay variable was selected, we would have to show the "simple markers" using data from the map-markers request.  If a categorical overlay variable is selected, we'd need to perform an additional barplot request (using the geohash variable as facetVariable). If a continuous overlay variable is selected, then we'd similarly do a geohash-faceted histogram request.  Then  we merge the results somehow and show the donut or histogram map markers.
