### ISSUE TITLE
Backend: add paging to the Data Table plugin to support subsetting tab Data Table View

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaDataService#48]
introduce an optional pagingConfig property

`  API_PagingConfig:
    type: object
    properties:
      numRows: integer
      offset: integer`

**Comment by d-callan** [comment]
i think this is ready in a branch, but depends on work in an identically named branch in the subset service which i dont think has been merged yet. @steve-fischer-200

**Comment by d-callan** [comment]
didnt know this was for subset tab as well? but in any case its merged

**Comment by nkittur-uga** [comment]
Talked with Danielle and was told that until the client actually uses it for something it's not really testable/ can't be QAed. 
The group will discuss how/when to QA backend features.

**Comment by danicahelb** [comment]
this ticket describes an obsolete approach to serving data to @eikonomega's table
