### ISSUE TITLE
new binStart option for *-histogram-bin-width

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#5]
In the use-case of EDA histogram filters we need to

1. request a "sensible default bin width" histogram for **unfiltered** query
2. (cache this 'background histogram' until the bin width is changed by the user)
3. request histogram for **filtered** data with binStart and binWidth that come from response of 1.

This is to ensure that the foreground (pink) and background (grey) bars use exactly the same bins.  It would be OK to trim/skip leading zero count bins.

So to clarify, the background histogram could have bins starting at 5, binwidth 5, going up 65.  The filtered data might be in the range 42-52, but its bins need to be 40-45, 45-50, 50-55.

**Comment by d-callan** [comment]
so i think we can do this w viewport ? ill just have, like binWidth, the default viewport used to calculate bins when one isnt provided be returned as part of the response. then you can pass that viewport through the second request.

**Comment by d-callan** [comment]
ive added the viewport used for binning to the response. since binning relies only on that and the specified binWidth/ numBins. you should be able to use the config in the first response to feed the second request. closing this. re-open if you disagree.
