### ISSUE TITLE
histogram: weekly date binning is off by one day

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#51]
/apps/pass/visualizations/histogram

POST  (variable is enrollment date)
```
{
	"config": {
		"binSpec": {
			"type": "binWidth",
			"units": "week",
			"value": 1
		},
		"outputEntityId": "EUPATH_0000096",
		"valueSpec": "count",
		"viewport": {
			"xMax": "2009-06-01",
			"xMin": "2009-02-01"
		},
		"xAxisVariable": {
			"entityId": "EUPATH_0000096",
			"variableId": "EUPATH_0000151"
		}
	},
	"filters": [],
	"studyId": "GEMSCC0003-1"
}
```
response - start of `binLabel` (but `binStart` and `binEnd` contain the same dates)
```
0 | "2009-01-26 - 2009-01-31"
1 | "2009-02-02 - 2009-02-07"
2 | "2009-02-09 - 2009-02-14"
3 | "2009-02-16 - 2009-02-21"
```

It seems like binEnd should be one day later (or binStart one day earlier!).  

Note: with 2 week binning, the bins look good (no gap between them)

Note 2: the missing days seem to be Sundays.   I'll check a different dataset or variable that may have data for Sundays.  No actually I won't  - because the 2-week binning is fine, and there are Sundays at the end of those bins too!

**Comment by d-callan** [comment]
this should be resolved plot.data v1.0.0
