### ISSUE TITLE
conttable: yLabel property in response is the wrong type

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/EdaDataService#52]
The `yLabel` property of the response is a `string[][]`. It should just be a `string[]`. The labels are repeated. This appears to be an issue for both 2x2 and RxC.

E.g.,
```json
{
	"yLabel": [
		[
			"Bury",
			"Bush/field/ground/stream/open sewer (includes dumping anywhere in environment outside compound)",
			"Do nothing",
			"Other",
			"Scatter in yard",
			"Toilet, latrine",
			"Unknown",
			"Ventilated improved pit with water seal"
		],
		[
			"Bury",
			"Bush/field/ground/stream/open sewer (includes dumping anywhere in environment outside compound)",
			"Do nothing",
			"Other",
			"Scatter in yard",
			"Toilet, latrine",
			"Unknown",
			"Ventilated improved pit with water seal"
		],
		[
			"Bury",
			"Bush/field/ground/stream/open sewer (includes dumping anywhere in environment outside compound)",
			"Do nothing",
			"Other",
			"Scatter in yard",
			"Toilet, latrine",
			"Unknown",
			"Ventilated improved pit with water seal"
		],
		[
			"Bury",
			"Bush/field/ground/stream/open sewer (includes dumping anywhere in environment outside compound)",
			"Do nothing",
			"Other",
			"Scatter in yard",
			"Toilet, latrine",
			"Unknown",
			"Ventilated improved pit with water seal"
		],
		[
			"Bury",
			"Bush/field/ground/stream/open sewer (includes dumping anywhere in environment outside compound)",
			"Do nothing",
			"Other",
			"Scatter in yard",
			"Toilet, latrine",
			"Unknown",
			"Ventilated improved pit with water seal"
		],
		[
			"Bury",
			"Bush/field/ground/stream/open sewer (includes dumping anywhere in environment outside compound)",
			"Do nothing",
			"Other",
			"Scatter in yard",
			"Toilet, latrine",
			"Unknown",
			"Ventilated improved pit with water seal"
		],
		[
			"Bury",
			"Bush/field/ground/stream/open sewer (includes dumping anywhere in environment outside compound)",
			"Do nothing",
			"Other",
			"Scatter in yard",
			"Toilet, latrine",
			"Unknown",
			"Ventilated improved pit with water seal"
		],
		[
			"Bury",
			"Bush/field/ground/stream/open sewer (includes dumping anywhere in environment outside compound)",
			"Do nothing",
			"Other",
			"Scatter in yard",
			"Toilet, latrine",
			"Unknown",
			"Ventilated improved pit with water seal"
		]
	]
}
```

**Comment by d-callan** [comment]
so i think i did this intentionally, in case one of the x values doesnt have all y values. i dont think im returning explicit 0 values anywhere else, so i didnt want to assume it here.

**Comment by dmfalke** [comment]
In other words, an element of `value` may have fewer entries than the others, and we should use the `yLabel` field to determine which counts go with which values?

This doesn't seem great to me. I'd like to propose an alternative data structure:

```typescript
type MosaicData = {
  [Xlabel: string]: {
    [Ylabel: string]: number;
  }
}
```

If we used that, then this:

```json
{
  "data": [
    {
      "xLabel": [
        "No",
        "Yes"
      ],
      "yLabel": [
        [
          "No",
          "Yes"
        ],
        [
          "No",
          "Yes"
        ]
      ],
      "value": [
        [
          18405,
          1092
        ],
        [
          3070,
          0
        ]
      ]
    }
  ]
}
```


would become this:

```json
{
  "data": {
    "No": {
      "No": 18405,
      "Yes": 1092
    },
    "Yes": {
      "No": 3070,
      "Yes": 0
    }
  }
}
```


This latter data structure is more concise, but also a little more clear (to me, at least) in how the labels and values are associated. Thoughts?

**Comment by dmfalke** [comment]
Note, we can use the variable metadata's `vocabulary` property to iterate on the complete set of values.

**Comment by d-callan** [comment]
I agree its not ideal.. it was a bit of a compromise bc the way it's currently structured aligns well w the structure of the underlying R object and so can be converted to json more or less automatically. I'll think on it some, see how I can either rearrange the R object or flag this case somehow to print it in some custom way maybe.

**Comment by dmfalke** [comment]
If it's a pain to do this in R, then we can leave it as-is. It would be pretty easy to convert it to my suggested structure in Javascript. Really, I just don't want to pass around the current data structure, since I think it's a potential source of bugs. The conversion can be done in Javascript as the data is retrieved from the backend.

**Comment by d-callan** [comment]
if its easy for you, thats probably the way to go. if it becomes a problem again, we can always revisit.

**Comment by d-callan** [comment]
did we decide what were doing? should this be closed?

**Comment by dmfalke** [comment]
let's just close this and keep things as they are. it's working now.
