### ISSUE TITLE
Variable constraints: inconsistent naming

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/EdaDataService#53]
At least in the bar plot plugin, the data element names are not consistent between `dataElementConstraints` and `dataElementDependencyOrder`: `overlayVariable` is used for the former, and `over` is used for the latter. The causes the client to not apply the constraints properly.

**Comment by dmfalke** [comment]
From what I can tell, box plot is the only plugin that exhibits this issue.

**Comment by d-callan** [comment]
fixed v1.2.2
