### ISSUE TITLE
Date bin consistency between Distribution and Histogram endpoints

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#54]
Distribution request (UMSP observation date, FWIW) for a very narrow range:
```
{
	"binSpec": {
		"binUnits": "day",
		"binWidth": 1,
		"displayRangeMax": "2016-08-04T00:00Z",
		"displayRangeMin": "2016-08-02T00:00Z"
	}
}
```
the response is three bins where end-date = start-date+1,
and this means the request range is inclusive (as if the request was actually "displayRangeMax": "2016-08-04T23:59Z",
```
{
	"histogram": [
		{
			"value": 1197,
			"binStart": "2016-08-02",
			"binEnd": "2016-08-03",
			"binLabel": "2016-08-02"
		},
		{
			"value": 1193,
			"binStart": "2016-08-03",
			"binEnd": "2016-08-04",
			"binLabel": "2016-08-03"
		},
		{
			"value": 1163,
			"binStart": "2016-08-04",
			"binEnd": "2016-08-05",
			"binLabel": "2016-08-04"
		}
	]
}
```
I have no issues with that, but it's different compared to the pass-through/histogram endpoint.

Here's GEMS1 histogram endpoint with a similar 3-day inclusive request:
```
{
	"config": {
		"binSpec": {
			"type": "binWidth",
			"units": "day",
			"value": 1
		},
		"outputEntityId": "EUPATH_0000096",
		"valueSpec": "count",
		"viewport": {
			"xMax": "2006-02-05",
			"xMin": "2006-02-03"
		},
		"xAxisVariable": {
			"entityId": "EUPATH_0000096",
			"variableId": "EFO_0004950"
		}
	}
}
```
it also returns three bins but the binEnds are the same as the binStarts:
```
{
	"0": {
		"binLabel": [
			"2006-02-03 - 2006-02-03",
			"2006-02-04 - 2006-02-04",
			"2006-02-05 - 2006-02-05"
		],
		"binStart": [
			"2006-02-03T00:00:00",
			"2006-02-04T00:00:00",
			"2006-02-05T00:00:00"
		],
		"binEnd": [
			"2006-02-03T00:00:00",
			"2006-02-04T00:00:00",
			"2006-02-05T00:00:00"
		],
		"value": [
			8,
			3,
			3
		]
	}
}
```
If we look at monthly bins (week bins for histogram have a known issue, see #51)

the distribution endpoint returns
```
{
	"0": {
		"value": 151,
		"binStart": "2006-01-01",
		"binEnd": "2006-02-01",
		"binLabel": "Jan 2006"
	}
}
```

the histogram endpoint returns 
`binStart: "2006-01-01T00:00:00", binEnd: "2006-01-31T00:00:00", binLabel: "2006-01-01 - 2006-01-31"`

So both approaches are consistent within themselves (apart from the weekly bug in #51) 

Neither is right or wrong - in fact both have advantages/disadvantages - we just need to decide on one approach!

For now, I will add a boolean switch prop to the Histogram component to perform the end-of-day adjustment (required for histogram endpoint, not required for distribution endpoint)

Attn: @ryanrdoherty @d-callan

**Comment by ryanrdoherty** [comment]
end values in the distribution endpoint are always exclusive.  This is necessary for floating point values (where you can't really specify and inclusive end and an inclusive start.  For dates the idea is that we are compatible with date-time values (support data values with the time component).  I originally had the binStart/binEnd values formatted with the time component, further illustrating the exclusiveness of the end value, but I thought trimming it would be more clear.  Maybe not?  The exception is that the final bin end IS inclusive.  This prevents an extra bin in the case of e.g. 0-10, binSize 2 (still get 5 bins, not 6 (10-12)).

**Comment by d-callan** [comment]
i think when i first drafted the histo endpoint i was doing it ryan's way also, and then decided it wasnt needed if the smallest bin was 'day' and were stripping times from the response anyhow. but thats probably a bad assumption, dont know what the future holds. i can change it. but should we then include the time in the response?

**Comment by d-callan** [comment]
ill do it ryans way, wo the time for now.

**Comment by bobular** [comment]
There was something nice about your way, @d-callan, having `binStart: 2001-03-01 binEnd: 2001-03-31` but Ryan's way eliminates the adjustment to "end of day" in the histogram plot component.  Six of one, half a dozen of the other!

For now I have just added an option to the histogram plot component to switch between the two behaviours.

**Comment by bobular** [comment]
I think we have to check what the filters are doing too.
Here I've set up a filter for two days - 18-20 Jan 2010
![image](https://user-images.githubusercontent.com/308639/126015503-6c279c5f-cbef-4f46-b96d-edb85a0da18a.png)

The filters sent to the back end look like
```
{
	"0": {
		"entityId": "EUPATH_0000096",
		"max": "2010-01-20T00:00Z",
		"min": "2010-01-18T00:00Z",
		"type": "dateRange",
		"variableId": "EFO_0004950"
	}
}
```

However I think this is behaving "inclusively" with respect to the end date, because look here at the histogram **visualization** with the same filter.  It's the same 22 participants as before, but they come from three days not two.

![image](https://user-images.githubusercontent.com/308639/126015653-253e0605-c009-482d-96f9-478494bebca2.png)

**Comment by d-callan** [comment]
ive updated the histo endpoint to do the same as ryan is in the distribution endpoint wrt bin ends for dates.

**Comment by d-callan** [comment]
is the filters issue for the subsetting service? im not sure im following..

**Comment by bobular** [comment]
Yes I think the filters issue is a subsetting thing.

**Comment by bobular** [comment]
Hi again @d-callan - I noticed that for dates the binStarts have an unwanted leading opening bracket e.g. `[2003-01-01T00:00:00`
And the binEnds have a stray closing parenthesis e.g. `2003-02-01)T00:00:00`

numeric variables seem fine :-)

**Comment by d-callan** [comment]
ive removed the parens. how does closing this and opening a new issue for the filters sound?

**Comment by bobular** [comment]
Yes that sounds good, thanks Danielle.

**Comment by d-callan** [comment]
i see the new ticket open, so ill close this one
