### ISSUE TITLE
boxplot response has key-value where key is tricky to validate - suggest xVariableValues instead

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#56]
See comment [here](https://github.com/VEuPathDB/web-eda/pull/120#discussion_r670575238)

We already get the info about the xVariable itself from
`boxplot.config.xVariableDetails.entityId` and `boxplot.config.xVariableDetails.variableId`

So just using something like `xVariableValues` as the key would make response validation in the client simpler.

**Comment by d-callan** [comment]
i used `label` to be consistent w other plots (ex: bar). should be resolved plot.data v1.0.0
