### ISSUE TITLE
Backend: need to change line plot to time series plot

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#57]
that means updating names and descriptions, but also figuring how to include the annotations indicating when a var represents time as part of variable constraints

**Comment by d-callan** [comment]
or maybe, since mbio wants line plots. make a new time series plot, and just change the included projects for the existing line plot to only mbio

**Comment by d-callan** [comment]
think we can maybe use the isTemporal annotation to add a 'temporal' data shape? dont think thats doable phase 1 though.

**Comment by danicahelb** [comment]
i removed the question label. We will be using the "is_temporal" annotation property in the .owl to identify temporal terms.

**Comment by nkittur-uga** [comment]
This is a backend thing and the decision is made, so there's nothing to QA here. Moving to complete.
