### ISSUE TITLE
*-histogram-* should explicitly return 0 values

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#6]

**Comment by steve-fischer-200** [comment]
what is the need for this?  what is the issue in the client this addresses?  (and, what is the priority?)

**Comment by d-callan** [comment]
Maybe w a continuous xaxis it's no longer an issue for the client, but when they were strings it caused things like 3 discontinuous bins to be returned when 5 were requested.

**Comment by steve-fischer-200** [comment]
@bobular please, given danielle's comment above, either close this ticket or indicate that it is needed

**Comment by bobular** [comment]
Yes, it was an issue in the past when the Histogram Plot used string labels, instead of a continuous axis.

They aren't needed any more.  Though the sort order (#1) is still desirable (if not, the plot component needs to do more work to figure out the x axis range).

Good catch.
