### ISSUE TITLE
Backend: RxC with X Var=Categorical numeric causes malformed sampleSizeTable

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaDataService#66]
Request (GEMS1)
```
{
	"config": {
		"outputEntityId": "EUPATH_0000096",
		"xAxisVariable": {
			"entityId": "EUPATH_0000096",
			"variableId": "EUPATH_0015720"
		},
		"yAxisVariable": {
			"entityId": "EUPATH_0000096",
			"variableId": "EUPATH_0010055"
		}
	},
	"filters": [],
	"studyId": "GEMSCC0003-1"
}
```
Response fragment
```
{
	"sampleSizeTable": [
		{
			"size": 22567
		}
	]
}
```
The client validator (and the API Docs) are expecting size to be an array of number.

I think it's because this is a categorical number variable.  String categoricals in the same entity work fine.

**Comment by asizemore** [comment]
I think I found the issue and will have a draft PR in plot.data shortly. Looks like we had multiple malformed sampleSizeTables, but this one with categorical numbers was the loudest.

**Comment by asizemore** [comment]
See [plot.data PR](https://github.com/VEuPathDB/plot.data/pull/69)

**Comment by asizemore** [comment]
Addressed with plot.data [PR 69](https://github.com/VEuPathDB/plot.data/pull/69).

**Comment by danicahelb** [comment]
This still seems to be an issue:

![image](https://user-images.githubusercontent.com/25450900/130278492-5dceb62c-21e7-49c8-b0a1-9e9e8e648778.png)

**Comment by danicahelb** [comment]
@asizemore assigning back to you, issues haven't been addressed

**Comment by d-callan** [comment]
not sure this is specific to cat nums. another possible duplicate of veupathdb/plot.data#79

**Comment by asizemore** [comment]
Testing locally, the variables above work (see screenshot). Still not sure what is causing the issue in qa

<img width="926" alt="Screen Shot 2021-08-23 at 1 29 20 PM" src="https://user-images.githubusercontent.com/11710234/130617099-2173554a-ee3c-4890-91a5-bef2f934f831.png">

**Comment by d-callan** [comment]
this is also working on qa after sorting out some recent issues deploying things. re-closing.

**Comment by SheenaTomko** [comment]
Tested in GEMS and SCORE and looks good.
