### ISSUE TITLE
numeric-histogram-bin-width will occasionally return 500 when filters are provided

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/EdaDataService#7]
I'm guessing all data is filtered away. I don't have an example at the moment, but I will try to provide one soon.

**Comment by d-callan** [comment]
do we have an ex of this?

**Comment by dmfalke** [comment]
This is an example of a request that fails with filters:

```sh
curl 'https://feature.clinepidb.org/eda-data/apps/pass/visualizations/date-histogram-bin-width' \
  -H 'Content-Type: application/json' \
  --data-raw '{"studyId":"GEMSCC0002-1","filters":[{"entityId":"PCO_0000024","variableId":"ENVO_00000004","stringSet":["Bangladesh","Kenya"],"type":"stringSet"}],"config":{"outputEntityId":"EUPATH_0000096","valueSpec":"count","xAxisVariable":{"entityId":"EUPATH_0000096","variableId":"EUPATH_0000151"},"binWidth":"month years"}}'
```

**Comment by d-callan** [comment]
it looks like that bin width isnt valid. (aside: once we have units separate it will be easier to validate bin widths for date histos..)

**Comment by dmfalke** [comment]
I think that binWidth is coming from a previous call with no filters or binWidth supplied. The idea is to use the same binWidth for both calls so that bins line up nicely. How is the binWidth invalid?

**Comment by d-callan** [comment]
so the underlying function i use to bin dates has this for documentation: 'one of ‘"sec"’, ‘"min"’, ‘"hour"’, ‘"day"’, ‘"DSTday"’, ‘"week"’, ‘"month"’, ‘"quarter"’ or ‘"year"’, optionally preceded by an integer and a space, or followed by ‘"s"’.'

**Comment by d-callan** [comment]
and currently my defaults are very simple. things like 'day', 'week', 'month', 'year'. theres room for growth there, i suppose

**Comment by dmfalke** [comment]
I didn't look closely at the POST body. I'm not sure where that value is coming from. I will investigate. Looks like a client bug.

**Comment by dmfalke** [comment]
It looks like there is an unpublished fix for this, so I think we can probably close this. Future bug reports should include an example.
