### ISSUE TITLE
Backend: need a pie plot endpoint (for map visualizations)

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#70]
this will call plot.data::bar, except it will have different variable constraints and no overlay var, barmode etc. dont know about proportions option. think its needed for the map.

**Comment by d-callan** [comment]
some comments from bob: 
This will be very similar to a barplot endpoint, but when used in the map visualization the variable constraints will need to allow an effectively unlimited number of facets. At the same time, overlay strata should be disallowed.

The constraints on the main variable are an interesting one too... In MapVEu 1.0 we had a limited number of colours (20) and then used varying shades of grey for the remaining pie segments. So t[here](https://veupathdb.github.io/web-components/?path=/story/map-donut-markers--all-in-one-request) was no constraint on the number of values that categorical values took. This is the one benefit of the pie/donut over bar plots - the "other" categories can be lumped together effectively as one grey pie. The downside to allowing unlimited pie segments is that the legend can become very unwieldy... I would be happy if the back end aggregated all the "others" into one pie slice (as is demoed with static data here). So yeah - we do need a new endpoint for this, @d-callan, as you suggested all along!!

Maybe call it geo-pie or something, in case we want a regular pie endpoint at a later date?

**Comment by d-callan** [comment]
@bobular in general in the eda cases like you describe for the main variable having more than 8 categories we would simply constrain against that term and direct the user to make a derived variable when we have them.. is there a reason thats not viable here?

**Comment by SheenaTomko** [comment]
Have pie plots on maps
