### ISSUE TITLE
Visualizations: bug hit when selecting variables for GEMS1

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaDataService#75]
For GEMS1 case control

![image](https://user-images.githubusercontent.com/25450900/130279306-1cfb21cf-15be-47c8-a562-767b834cab3a.png)

**Comment by d-callan** [comment]
duplicate of veupathdb/plot.data#79

**Comment by danicahelb** [comment]
This still isn't working but I am now getting a different error message:

![image](https://user-images.githubusercontent.com/25450900/131524307-13bb1106-5d7e-4a41-b10f-8c6b065d79dc.png)

**Comment by dmfalke** [comment]
I may have missed an update for the backend. I will double-check.

**Comment by moontrip** [comment]
@danicahelb yes as @dmfalke said, I think it is because the front-end update is not deployed to qa site yet. It just worked fine at my local VM: screenshot is attached. 

![RxC1](https://user-images.githubusercontent.com/12802305/131539490-7d248ba2-1089-4d2d-8ef9-fc3a5bcf7c49.png)

**Comment by dmfalke** [comment]
I've upgraded the service used on the qa site. Please check again @danicahelb. Thanks!

**Comment by dmfalke** [comment]
There may be a delay before the upgraded service is deployed. Might be good to wait until 3pm edt.

**Comment by dmfalke** [comment]
I've confirmed that the error is now fixed

**Comment by danicahelb** [comment]
this issue now passed QA, thanks all
