### ISSUE TITLE
Need to expose the paged /tabular endpoint

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaDataService#78]
the subset service has a variant of the /tabular endpoint that supports paging.  this needs to be exposed thru the data service to drive the subset tab Data Table view (one entity at a time).

the API should be very similar to the existing data table viz plugin.

options:

1. create a data service plugin to read the tabular data from the sss and output the expected JSON.  will require the data service to see the subsetting service directly
2. similar to above, but use the existing plugin.   if it detects that all variables are from the desired entity, switch to the efficient sss endpoint
3. update the sss endpoint to output the same json as the data service plugin, and pass it thru the data service.

i think i like (2) best, because the API for these requests are identical.  the swapping in of the subsetting service as a raw provider is a performance optimization.   this principle could also be applied to the /distrubtion endpoint.  in general, it probably makes sense to give the data service direct access to the subsetting service, unless there are countervailing considerations i'm not aware of

**Comment by d-callan** [comment]
does the decision to push sorting to phase 2 make this a phase 2 issue now?

**Comment by danicahelb** [comment]
@steve-fischer-200 @dmfalke I don't think I understand this ticket & how important it is to work on it sooner vs later

**Comment by danicahelb** [comment]
@eikonomega is this related to https://github.com/VEuPathDB/web-eda/issues/261?

**Comment by ryanrdoherty** [comment]
All the work on the backend is complete to support this in both JSON and tabular formats, and the tabular endpoint is available both on eda-data and directly on the subsetting service.  Format is controlled by the Accept header.  Use either "application/json" or "text/tab-separated-values".

**Comment by SheenaTomko** [comment]
Doesn't seem like this can be qa'd until the subset table and download is available

**Comment by danicahelb** [comment]
I'm closing this ticket

@eikonomega if you see any issues going forward, please open a new ticket for it
