### ISSUE TITLE
date-histogram-* plugins are not working

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/EdaDataService#8]
They return a 500 response code.

**Comment by d-callan** [comment]
date-histogram-* plugins should be generally working now w the exception that trying to request a specific number of bins from date-histogram-num-bins gives a 500. im closing this and opening a separate issue for that, since i suspect the priority for that falls below profiling for performance.

**Comment by dmfalke** [comment]
I'm still getting 500s:

```
curl 'https://dfalke-b.clinepidb.org/eda-data/apps/pass/visualizations/date-histogram-bin-width' \
  -H 'Content-Type: application/json' \
  --data '{"studyId":"GEMSCC0002-1","filters":[],"config":{"outputEntityId":"EUPATH_0000096","valueSpec":"count","xAxisVariable":{"entityId":"EUPATH_0000096","variableId":"EFO_0004950"}}}' 
```

**Comment by dmfalke** [comment]
I'm reopening. Feel free to close if I'm missing something :)

**Comment by d-callan** [comment]
the rserve container was failing to build, and so wasnt reflecting my recent changes. this is now resolved and im re-closing the ticket
