### ISSUE TITLE
update var constraints for all vizs

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#87]
any place we currently write constraints on data shape of continuous, we should use data type of number/ date instead. this is to avoid the arbitrary inference of terms as categorical at fewer than 10 unique values. at a minimum, this will allow us the opportunity to identify how large a problem/ how many categorical number vars we actually have.

we also need to add a human-readable description to each of the variable constraints.

**Comment by d-callan** [comment]
we could also consider removing constraints on categorical data shape (functionally ignoring data shape entirely) and add constraints on the number of values + data type only.

**Comment by asizemore** [comment]
Dropping a note that these constraint descriptions may also be helpful on this Learn More page.
<img width="370" alt="Screen Shot 2021-09-08 at 10 13 28 AM" src="https://user-images.githubusercontent.com/11710234/132558585-56526490-9f19-43fb-a6dc-80c7a07e476d.png">

**Comment by danicahelb** [comment]
seems OK, but I am waiting for https://github.com/VEuPathDB/web-eda/issues/310 to pass QA before moving to 'Complete'
