### ISSUE TITLE
*-histogram-* binWidth in response is not accurate

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/EdaDataService#9]
The `binSize` property in the responses config object does not match the `binStart` array.

**Comment by bobular** [comment]
binWidth?

**Comment by d-callan** [comment]
Believe this is resolved. Please re-open if I'm proved wrong.
Note: the bin labels, and consequently bin start and end are rounded for readability, but not in any way that affects which records contribute to each bin. It's just that the bin start + bin width calc may give something that is say a hundredth off the reported bin end.
