### ISSUE TITLE
Visualizations: overlay variable constraints not working properly

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaDataService#93]
In GEMS1 scatterplot, i selected Participant repeated measure variables for both the x and y axes. I then was able to select a household repeated measure variable for the overlay and got the following error message:

![image](https://user-images.githubusercontent.com/25450900/133332701-a5dc729d-2c38-4389-96c3-fd2a68150e26.png)

**Comment by moontrip** [comment]
@danicahelb Please check this behavior again as the overlay is not selectable anymore: tested at https://qa.clinepidb.org/. There might have been changes at either frontend or backend like addressed at other issue since your initial tests

**Comment by d-callan** [comment]
duplicates veupathdb/web-eda#318 which @dmfalke says hes already fixed

**Comment by SheenaTomko** [comment]
Looks good. Can no longer choose human waste facilities for the overlay since it's on a different branch, but can choose community, household, participant, and participant repeated measure variables
