### ISSUE TITLE
Visualizations: organize icons of available visualizations

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#97]
It might be nice to have the icons indicating available visualizations organized somehow. like perhaps by whether they (excluding strata) are single, bi- or multi-variate.

**Comment by d-callan** [comment]
pushed to master and tagged as v1.5.3

**Comment by danicahelb** [comment]
i think vis tools 1-6 are the ones most likely to be used, so i think we will only have to organize the new ones in. i'm not sure how to automate this, but am willing to hear ideas.

I'll check in about "record count", if we come up with a better label i will make a new ticket. thanks!

**Comment by nkittur-uga** [comment]
Viz tools are well-organized. QA is complete.
