### ISSUE TITLE
Visualizations: update var constraints to include new Integer dataType

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaDataService#98]
first pass, just add integer to any place we currently constrain on number.

**Comment by SheenaTomko** [comment]
I don't think this is working on the new sites properly. I just tested in a few studies and integer data is still inaccessible in multiple visualizations. For example, in GEMS1A histograms, all these variables in the screenshot that are integers (counts) are unavailable, but the one numeric variable is accessible

<img width="330" alt="Screen Shot 2021-09-29 at 11 07 34 AM" src="https://user-images.githubusercontent.com/54597319/135307131-cb31dd85-9bc1-43e1-917b-dd1164aedf6a.png">

**Comment by d-callan** [comment]
feature site is updated, should be working there now.

**Comment by SheenaTomko** [comment]
Integer variables are now accessible in the visualization tools. However there seem to be some bugs in some tools when using integer variables with <10 values. I'll make new tickets for each tool with an issue (since not all tools seem to be affected). Closing this ticket
